-- Group battle SCHEDULING + AUTO-PAIRING (feature: "chủ group đặt lịch đấu").
-- Adds a scheduled time + play window to group_battles, and a pairing board that maps
-- members of the two groups 1-vs-1. Timeout rules are enforced client-side (same
-- pattern as the weekly prizes): a pair where only one side joined within the window
-- loses for the absent side; a pair where neither joined is a draw.
--
-- Run this whole file once in the Supabase SQL editor.

alter table public.group_battles add column if not exists scheduled_at timestamptz;
alter table public.group_battles add column if not exists window_min int not null default 30;

create table if not exists public.group_battle_pairs (
  id uuid primary key default gen_random_uuid(),
  battle_id uuid not null references public.group_battles(id) on delete cascade,
  user_a_id uuid not null references public.profiles(id) on delete cascade,
  username_a text not null,
  user_b_id uuid not null references public.profiles(id) on delete cascade,
  username_b text not null,
  joined_a_at timestamptz,
  joined_b_at timestamptz,
  -- 'a' | 'b' side won, or 'draw'. Null while undecided.
  winner text check (winner in ('a', 'b', 'draw')),
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists group_battle_pairs_battle_idx on public.group_battle_pairs (battle_id);

alter table public.group_battle_pairs enable row level security;

-- The pairing board is public info (any logged-in user can view a battle card).
create policy group_battle_pairs_select_all on public.group_battle_pairs
  for select to authenticated using (true);

-- Pairs are generated by an admin of either battling group (at accept time).
create policy group_battle_pairs_insert_by_admin on public.group_battle_pairs
  for insert to authenticated with check (
    exists (
      select 1 from public.group_battles b
      join public.group_members m on m.group_id in (b.group_a_id, b.group_b_id)
      where b.id = battle_id
        and m.user_id = auth.uid()
        and m.status = 'active'
        and m.role in ('owner', 'admin')
    )
  );

-- The two participants update their own join timestamps; admins of either group may
-- also update (that covers the client-driven timeout finalization).
create policy group_battle_pairs_update_participants on public.group_battle_pairs
  for update to authenticated using (
    auth.uid() in (user_a_id, user_b_id)
    or exists (
      select 1 from public.group_battles b
      join public.group_members m on m.group_id in (b.group_a_id, b.group_b_id)
      where b.id = battle_id
        and m.user_id = auth.uid()
        and m.status = 'active'
        and m.role in ('owner', 'admin')
    )
  );

-- Scheduled battles should be visible to everyone (the schedule/pair board is public),
-- widening the old members-only select. Safe: battles contain no private data.
drop policy if exists group_battles_select_members on public.group_battles;
create policy group_battles_select_all on public.group_battles
  for select to authenticated using (true);
